version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      mui:
        patterns:
          - '@mui/*'
      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'
          - 'eslint-plugin-storybook'
      emotion:
        patterns:
          - '@emotion/*'
      testing:
        patterns:
          - 'vitest'
          - '@vitest/*'
          - '@testing-library/*'
      next:
        patterns:
          - 'next'
          - 'eslint-config-next'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
